2018-11-12 07:30:07.516182: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-11-12 07:30:11.764345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla K40m major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:82:00.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2018-11-12 07:30:11.764412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-11-12 07:30:17.721480: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-12 07:30:17.721542: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2018-11-12 07:30:17.721555: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2018-11-12 07:30:17.722002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10750 MB memory) -> physical GPU (device: 0, name: Tesla K40m, pci bus id: 0000:82:00.0, compute capability: 3.5)
2018-11-12 07:30:29.517941: E tensorflow/stream_executor/cuda/cuda_dnn.cc:363] Loaded runtime CuDNN library: 7.0.5 but source was compiled with: 7.1.4.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2018-11-12 07:30:29.519431: E tensorflow/stream_executor/cuda/cuda_dnn.cc:363] Loaded runtime CuDNN library: 7.0.5 but source was compiled with: 7.1.4.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Using TensorFlow backend.
/home/ICTDOMAIN/d14122793/code/ucf101_full_classes/models.py:198: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(64, (3, 3, 3), activation="relu", padding="same", input_shape=(40, 80, 8..., name="conv1", strides=(1, 1, 1))`
  input_shape=self.input_shape))
/home/ICTDOMAIN/d14122793/code/ucf101_full_classes/models.py:200: UserWarning: Update your `MaxPooling3D` call to the Keras 2 API: `MaxPooling3D(padding="valid", name="pool1", pool_size=(1, 2, 2), strides=(1, 2, 2))`
  border_mode='valid', name='pool1'))
/home/ICTDOMAIN/d14122793/code/ucf101_full_classes/models.py:204: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(128, (3, 3, 3), activation="relu", padding="same", name="conv2", strides=(1, 1, 1))`
  subsample=(1, 1, 1)))
/home/ICTDOMAIN/d14122793/code/ucf101_full_classes/models.py:206: UserWarning: Update your `MaxPooling3D` call to the Keras 2 API: `MaxPooling3D(padding="valid", name="pool2", pool_size=(2, 2, 2), strides=(2, 2, 2))`
  border_mode='valid', name='pool2'))
/home/ICTDOMAIN/d14122793/code/ucf101_full_classes/models.py:210: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(256, (3, 3, 3), activation="relu", padding="same", name="conv3a", strides=(1, 1, 1))`
  subsample=(1, 1, 1)))
/home/ICTDOMAIN/d14122793/code/ucf101_full_classes/models.py:213: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(256, (3, 3, 3), activation="relu", padding="same", name="conv3b", strides=(1, 1, 1))`
  subsample=(1, 1, 1)))
/home/ICTDOMAIN/d14122793/code/ucf101_full_classes/models.py:215: UserWarning: Update your `MaxPooling3D` call to the Keras 2 API: `MaxPooling3D(padding="valid", name="pool3", pool_size=(2, 2, 2), strides=(2, 2, 2))`
  border_mode='valid', name='pool3'))
/home/ICTDOMAIN/d14122793/code/ucf101_full_classes/models.py:219: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(512, (3, 3, 3), activation="relu", padding="same", name="conv4a", strides=(1, 1, 1))`
  subsample=(1, 1, 1)))
/home/ICTDOMAIN/d14122793/code/ucf101_full_classes/models.py:222: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(512, (3, 3, 3), activation="relu", padding="same", name="conv4b", strides=(1, 1, 1))`
  subsample=(1, 1, 1)))
/home/ICTDOMAIN/d14122793/code/ucf101_full_classes/models.py:224: UserWarning: Update your `MaxPooling3D` call to the Keras 2 API: `MaxPooling3D(padding="valid", name="pool4", pool_size=(2, 2, 2), strides=(2, 2, 2))`
  border_mode='valid', name='pool4'))
/home/ICTDOMAIN/d14122793/code/ucf101_full_classes/models.py:229: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(512, (3, 3, 3), activation="relu", padding="same", name="conv5a", strides=(1, 1, 1))`
  subsample=(1, 1, 1)))
/home/ICTDOMAIN/d14122793/code/ucf101_full_classes/models.py:232: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(512, (3, 3, 3), activation="relu", padding="same", name="conv5b", strides=(1, 1, 1))`
  subsample=(1, 1, 1)))
/home/ICTDOMAIN/d14122793/code/ucf101_full_classes/models.py:235: UserWarning: Update your `MaxPooling3D` call to the Keras 2 API: `MaxPooling3D(padding="valid", name="pool5", pool_size=(2, 2, 2), strides=(2, 2, 2))`
  border_mode='valid', name='pool5'))
Loading C3D
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv1 (Conv3D)               (None, 40, 80, 80, 64)    5248      
_________________________________________________________________
pool1 (MaxPooling3D)         (None, 40, 40, 40, 64)    0         
_________________________________________________________________
conv2 (Conv3D)               (None, 40, 40, 40, 128)   221312    
_________________________________________________________________
pool2 (MaxPooling3D)         (None, 20, 20, 20, 128)   0         
_________________________________________________________________
conv3a (Conv3D)              (None, 20, 20, 20, 256)   884992    
_________________________________________________________________
conv3b (Conv3D)              (None, 20, 20, 20, 256)   1769728   
_________________________________________________________________
pool3 (MaxPooling3D)         (None, 10, 10, 10, 256)   0         
_________________________________________________________________
conv4a (Conv3D)              (None, 10, 10, 10, 512)   3539456   
_________________________________________________________________
conv4b (Conv3D)              (None, 10, 10, 10, 512)   7078400   
_________________________________________________________________
pool4 (MaxPooling3D)         (None, 5, 5, 5, 512)      0         
_________________________________________________________________
conv5a (Conv3D)              (None, 5, 5, 5, 512)      7078400   
_________________________________________________________________
conv5b (Conv3D)              (None, 5, 5, 5, 512)      7078400   
_________________________________________________________________
zero_padding3d_1 (ZeroPaddin (None, 5, 7, 7, 512)      0         
_________________________________________________________________
pool5 (MaxPooling3D)         (None, 2, 3, 3, 512)      0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 9216)              0         
_________________________________________________________________
fc6 (Dense)                  (None, 4096)              37752832  
_________________________________________________________________
dropout_1 (Dropout)          (None, 4096)              0         
_________________________________________________________________
fc7 (Dense)                  (None, 4096)              16781312  
_________________________________________________________________
dropout_2 (Dropout)          (None, 4096)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 101)               413797    
=================================================================
Total params: 82,603,877
Trainable params: 82,603,877
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/1000
Creating train generator with 8596 samples.
Creating test generator with 3418 samples.
Traceback (most recent call last):
  File "train.py", line 119, in <module>
    main()
  File "train.py", line 116, in main
    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)
  File "train.py", line 83, in train
    workers=4)
  File "/home/ICTDOMAIN/d14122793/virtual_env/dl/ucf101/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ICTDOMAIN/d14122793/virtual_env/dl/ucf101/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/ICTDOMAIN/d14122793/virtual_env/dl/ucf101/lib/python3.5/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/ICTDOMAIN/d14122793/virtual_env/dl/ucf101/lib/python3.5/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/ICTDOMAIN/d14122793/virtual_env/dl/ucf101/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/ICTDOMAIN/d14122793/virtual_env/dl/ucf101/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/ICTDOMAIN/d14122793/virtual_env/dl/ucf101/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/ICTDOMAIN/d14122793/virtual_env/dl/ucf101/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv1/convolution}} = Conv3D[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/conv1/convolution_grad/Conv3DBackpropFilterV2"], data_format="NDHWC", dilations=[1, 1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_conv1_input_0_0/_191, conv1/kernel/read)]]
	 [[{{node metrics/top_k_categorical_accuracy/Mean_1/_231}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1601_metrics/top_k_categorical_accuracy/Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
